name: Manual Docker image build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'Build Environment'
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ghcr.io/toxoplasmotic/autogen:${{ github.event.inputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run AutoGen
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/toxoplasmotic/autogen:${{ github.event.inputs.version }}
        shell: bash
        run: tail ./agents/Accountant.md
